# Generated by Django 4.2 on 2024-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('MERCEDES', 'Mercedes'), ('TESLA', 'Tesla'), ('TOYOTA', 'Toyota'), ('BMW', 'Bmw'), ('AUDI', 'Audi')], max_length=200),
        ),
    ]
