# Generated by Django 4.2 on 2024-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_person_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
