# Generated by Django 4.2 on 2024-02-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_order_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
