version: "3.9"

services:
  app4:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - gunicorn
      - main_page.wsgi:application
      - --bind
      - "0.0.0.0:8003"
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200K"
    volumes:
      - ./dataanalytics/database:/app4/database